### ISSUE TITLE
Syntax colour highlighting of HTML with JSON context in JavaScript section

### ISSUE THREAD

**Issue by ajtruckle** [ScintillaOrg/lexilla#214]
I originally reported this issue on the Notepad++ forum. See the linked issue for explanation.

https://github.com/notepad-plus-plus/notepad-plus-plus/issues/14413

You can use `\` to split long lines of text over multiple lines in the editor for clarity. But the syntax highlighting goes not respect this. The second line after `\` should continue as a "string" colour. And ideally the `\` itself should be a different colour to make it stand out.

**Comment by ajtruckle** [comment]
@nyamatongwe 
Sorry, but what is the linked article really saying specific to my case? Thank you.

**Comment by mpheath** [comment]
@ajtruckle It is like a note to self as reference. Still as you mention, related to backslash escape though none in the examples at end of line like your example.

@nyamatongwe  My curiosity tingles as why single quotes have different behaviour to double quotes in Javascript when they are supposed to be interchangable.

Double quotes:

https://github.com/ScintillaOrg/lexilla/blob/6a977a3698ca9f1400805296ee6c994afad0904f/lexers/LexHTML.cxx#L2175-L2178

Single quotes:

https://github.com/ScintillaOrg/lexilla/blob/6a977a3698ca9f1400805296ee6c994afad0904f/lexers/LexHTML.cxx#L2188-L2193

I would expect these 2 code blocks to be the same. Surely one is right and the other is not. This is why I mentioned the workaround of trying single quotes in the linked post at Notepad++ as an immediate action to correct the styling.

Reference: https://www.javascript.com/learn/strings

**Comment by mpheath** [comment]
@nyamatongwe Thanks for the information. I did not consider the markdown at Scintilla got messed up, my mistake.

As they say, "*don't fix if not broke*". The bug fix done by Stephen Deibel appears to work with single quoted strings and I cannot seem to break it, so I'll go with the option to apply the same fix to the double quoted strings.

[issue214_1.zip](https://github.com/ScintillaOrg/lexilla/files/13473869/issue214_1.zip)

**Comment by ajtruckle** [comment]
I appreciate your closing the issue. But Notepad++ still renders my file as I originally reported. Does this commit mean Notepad++ will have another update with the newer editor control?

**Comment by mpheath** [comment]
@ajtruckle The issue is fixed and closed here at Lexilla. [Lexilla 5.3.0](https://www.scintilla.org/LexillaHistory.html) has been released with this fix.

Notepad++ will probably have a [Pull Request](https://github.com/notepad-plus-plus/notepad-plus-plus/pulls) submitted in a few days to merge the new releases of Scintilla and Lexilla. Time may depend on the holiday season.

If everything goes OK, the next release of Notepad++ will have this fix.

In SciTE 5.4.1 which has been just released with the fix looks like:
![html_escape](https://github.com/ScintillaOrg/lexilla/assets/58158242/1bc1bafa-4b3f-401f-aa77-d516eb84c7d7)

If you want the fix any quicker, then you may need to compile Notepad++ yourself with the fix.

>Does this commit mean Notepad++ will have another update with the newer editor control?

Expectation is yes as to the routine of Notepad++.
