### ISSUE TITLE
Markdown deadloop at function IsCompleteStyleRegion to proces token "`"  when type character continuous

### ISSUE THREAD

**Issue by halx99** [ScintillaOrg/lexilla#23]
https://github.com/ScintillaOrg/lexilla/blob/master/lexers/LexMarkdown.cxx#L126

**Comment by halx99** [comment]
Could be fixed as follow changes:
```cpp
static bool IsCompleteStyleRegion(StyleContext &sc, const char *token) {
    bool found = false;
	const size_t start = strlen(token);
    Sci_Position i = static_cast<Sci_Position>(start);
    int c;
    while ((c = sc.GetRelative(i)) && !IsNewline(c)) {
        // make sure an empty pair of single-char tokens doesn't match
        // with a longer token: {*}{*} != {**}
	    if (sc.GetRelative(i) == *token && sc.GetRelative(i - 1) != *token) {
		    found = start > 1U ? sc.GetRelative(i + 1) == token[1] : true;
			break;
		}
        i++;
    }
    return AtTermStart(sc) && found;
}
```

I don't know does it correct

Tips: sorry I post issue at here, because the sourceforge always disable my account, I have try register account of sourceforge many times

**Comment by RaiKoHoff** [comment]
It is more an infinite (`std::numeric_limits<int>::max()`) busy loop, which might occur as a deadlock.
Problem is `sc.GetRelative(i)` returns '\0' if out of range.
So another fix would be to change the local method for new line check:

```
// from:
static inline bool IsNewline(const int ch) {
    return (ch == '\n' || ch == '\r');
}

// to:
constexpr bool IsNewline(const int ch) {
    // sc.GetRelative(i) returns '\0' if out of range
    return (ch == '\n' || ch == '\r' || ch == '\0'); 
}
```

**Comment by rdipardo** [comment]
@RaiKoHoff, it would be simpler to call `GetRelative()` with its optional 2nd argument:
 
https://github.com/ScintillaOrg/lexilla/blob/ca4f0559ec6b9e554aa6bb864c3303125fd279dd/lexlib/StyleContext.h#L161-L163

```diff
-    while (!IsNewline(sc.GetRelative(i))) {
+    while (!IsNewline(sc.GetRelative(i, '\n'))) {
```
That way a random `NULL` can't be mistaken for a legitimate newline

**Comment by nyamatongwe** [comment]
The problem here appears to be that there is an infinite loop if the document ends with "`".

**Comment by rdipardo** [comment]
I get it now. 

In fact the same is true for all the style delimters (`*`, `**`,  `_`,  `__`,  `~~`).

@halx99's [correction](https://github.com/ScintillaOrg/lexilla/issues/23#issuecomment-893417214) appears to work in all cases:

![backtick](https://user-images.githubusercontent.com/59004801/128433065-d9e258a7-0ae4-469c-8e9c-d97d99e0a5de.png)
![star](https://user-images.githubusercontent.com/59004801/128433082-ddb4ab08-91d1-411b-957e-01527bab4a9a.png)
![star_2x](https://user-images.githubusercontent.com/59004801/128433088-dd1565d3-2c83-4e36-b624-aa624535222b.png)
![underscore](https://user-images.githubusercontent.com/59004801/128433091-20337029-05f9-4292-8215-813980821c52.png)
![underscore_2x](https://user-images.githubusercontent.com/59004801/128433102-17806467-ff41-4b5d-b181-613b2d19fda9.png)
![tildes](https://user-images.githubusercontent.com/59004801/128433400-a8af992c-4806-438f-bfeb-2cbefe4d3914.png)

**Comment by rdipardo** [comment]
On second thought, the cleaner solution is probably [@RaiKoHoff's](https://github.com/ScintillaOrg/lexilla/issues/23#issuecomment-893433424) (with or without overloading `GetRelative()`).

Turns out this very issue was found and fixed downstream some 2 weeks ago. You can obtain a patch by simply adding  ".diff" or ".patch" to this commit's URL: https://github.com/rizonesoft/Notepad3/commit/89b63940c47cdb8d6952765ec497776212a108d9

It needs minimal editing and compiles quietly even with MSVC at [warning level 4][], which has a problem with the earlier patch:

```
LexMarkdown.cxx(127): warning C4706: assignment within conditional expression [C:\Users\Rob\source\git\scintilla-contib\scite\win32\SciTE.vcxproj]
```

(gcc doesn't mind as long as the assignment is parenthesized.)

Here's the slightly updated test suite I used for verification:
- [0001-LexMarkdown-TestIssue23.diff.txt](https://github.com/ScintillaOrg/lexilla/files/6943559/0001-LexMarkdown-TestIssue23.diff.txt)

[warning level 4]: https://github.com/ScintillaOrg/lexilla/blob/2b36c2ed3491838acb580d4ba52bd20eac2e4aea/src/lexilla.mak#L39
