### ISSUE TITLE
[HTML] JavaScript basic support for template literal 

### ISSUE THREAD

**Issue by zufuliu** [ScintillaOrg/lexilla#280]
Basic support for template literal can be added with minor changes, while support `${}` interpolating (e.g. copy `interpolatingAtEol` from LexCPP) appears needs complex changes.

**Comment by nyamatongwe** [comment]
Adding `SCE_HJ_TEMPLATESTRING` and `SCE_HJA_TEMPLATESTRING` would be a reasonable minor change. Later, expression support could be incrementally added starting with simple cases with no new lines or nesting.

Due to nesting, some valid examples may lex worse than currently, terminating `SCE_HJ_TEMPLATESTRING` early. There could be an enabling property if this is a problem.

Complex example from `cpp` tests that currently lexes poorly embedded in JavaScript in HTML but the elements appear isolated. This may become a more confusing set of pieces with some pieces treated as template strings.
~~~javascript
`\${a${ `b${ `c${ JSON.stringify({
'4': {},
}) }d` }e` }f}`
~~~

Equivalent issue for `cpp` lexer was #94.

**Comment by zufuliu** [comment]
I think most of time template literal is just used as multiline string, interpolating is rare, nested interpolating is even rare. Just adding the styles should good enough for most cases.

**Comment by zufuliu** [comment]
[HTML-template-literal-1008.patch](https://github.com/user-attachments/files/17292323/HTML-template-literal-1008.patch)

Patch added template literal styles (using `SCE_HJ_TEMPLATELITERAL` and `SCE_HJA_TEMPLATELITERAL` from https://github.com/zufuliu/notepad4/commit/b0597af8409010bd2ad536ddcc8b85f85e49c139, I can rename them to use `_TEMPLATESTRING` if it maters).

following simple test is added into Issue273JavaScript.html
```js
var template = `
<?xml encoding='${encoding}'>
<!doctype>
`;
```

**Comment by nyamatongwe** [comment]
Committed. Minor change to order of tags in lexical class descriptions to be similar to other entries.
