### ISSUE TITLE
Python: line continuation situations sometimes fold incorrectly

### ISSUE THREAD

**Issue by Davidy22** [ScintillaOrg/lexilla#43]
In python, brackets ()[]{} and a slash \ at the end of a line allow a statement to be continued onto the next non-empty line, meaning that something like this:

```
if param2 <= 2:
    print((-20 %


3) / 5)
    else:
        print(1)
```

Is legal python where the first print() gives 0.2. Python lexilla only looks at indentation for folding though, so this folds up to the second line and the `3) / 5)` is treated like the beginning of a new block.

The above is true for and also occurs in the gdscript lexer.

Found in and continued from #41

**Comment by nyamatongwe** [comment]
It would be unusual to write this code in that form as Python programmers will commonly indent continued statements. Lexilla lexers and folders concentrate on languages as they are commonly written.

**Comment by Davidy22** [comment]
Oh, if we're just covering typical formatting and not all possible formatting then I guess this isn't an issue.

**Comment by mpheath** [comment]
I see invalid code. Let's look into this.

<details>
<summary>bat file to create "output.log"</summary>

```bat
> output.log call :test 2>&1
exit /b

:test
py -0
type test1.py
py test1.py
type test2.py
py test2.py
type test3.py
py test3.py
```

On Linux, `type` is like `cat` and `py` is like `python3`, except `py` is a launcher.

</details>

<details>
<summary>"output.log" in the directory "C:\Test"</summary>

```
C:\Test> py -0 
Installed Pythons found by py Launcher for Windows *


 -3.8-64
C:\Test> type test1.py 
param2 = 1

if param2 <= 2:
    print((-20 %


3) / 5)
    else:
        print(1)

C:\Test> py test1.py 
  File "test1.py", line 8
    else:
    ^
SyntaxError: invalid syntax

C:\Test> type test2.py 
param2 = 1

if param2 <= 2:
    print((-20 % 3) / 5)
    else:
        print(1)

C:\Test> py test2.py 
  File "test2.py", line 5
    else:
    ^
SyntaxError: invalid syntax

C:\Test> type test3.py 
param2 = 1

if param2 <= 2:
    print((-20 %


3) / 5)
else:
    print(1)

C:\Test> py test3.py 
0.2
```

Only `test3.py` is valid syntax as the `else` is at the same indent level as the `if`.

</details>

I am curious to know which Python interpreter would allow `test1.py`:

```py
param2 = 1

if param2 <= 2:
    print((-20 %


3) / 5)
    else:
        print(1)
```

or `test2.py` without continuation caused by the parentheses, as I expect the interpreter to read the previous code like:

```py
param2 = 1

if param2 <= 2:
    print((-20 % 3) / 5)
    else:
        print(1)
```

to run without error.

`test3.py` runs OK

```py
param2 = 1

if param2 <= 2:
    print((-20 %


3) / 5)
else:
    print(1)
```

and the code folding appears OK.

I added the `param2 = 1` else any test would error.

Look how Github colours the `else` as it's lexing surprisingly knows whether the `else` is valid or not. Impressive lexing, or lucky by chance.

The indent before the `else` cannot be ignored just because the previous line is a continued line. It needs to match the indent before the `if`.

This is valid Python code:

```py
def test():
    print(1 + 2)
    print(1 +
  2)
    print(1 +
              2)
    print('abc'
'def'
                    'ghi')
    print('\
abcdefghi')
    print('''The rules of indentation
does not apply to continuations as
they are resolved during parsing.
    print() for example, not this textual one, needs to be indented.''')

test()
```

Indenting requirements does not apply with a continued lines while the above shows indenting of 2, 4 or any other amount of spaces. It is valid as all of the `print` calls are indented 4 spaces.

@Davidy22, do you still consider the initial code as valid Python code?

**Comment by Davidy22** [comment]
Oh, whoops, I copied it from a test I had in a file where this was inside a function, nuked the indentation before the first `if` so the else has an excess indentation. The contents of `test3.py` were the intention, and they still fold incorrectly: this is what it looks like on its own:

![image](https://user-images.githubusercontent.com/872968/144346650-c1ea92c2-c6a5-4922-93d7-92a43148db18.png)

Note how the fold indicator on the side stops on line 17 instead of extend down to just before the `else`

**Comment by mpheath** [comment]
OK, please post the full reproducable code next time.

I see the same folding with SciTE.

Line 17 points to the start of the line instead of the end, which is line 20. Lexers are simple and doubt the code needed to find the line end would be worth it. The lexer would need to account for all continuation types and be able to interpret correctly to the end. The person who would implement this would deserve a rather large treat.
