### ISSUE TITLE
Support style value larger than 127

### ISSUE THREAD

**Issue by zufuliu** [ScintillaOrg/lexilla#61]
See https://sourceforge.net/p/scintilla/feature-requests/1431/

[lexilla-int-style.zip](https://github.com/ScintillaOrg/lexilla/files/8146025/lexilla-int-style.zip)

Patch contains following changes:
1. updated `LexAccessor::StyleAt()` and `LexAccessor::BufferStyleAt()` to returns `int` instead of `char`.
2. changed `char chMask` to `unsigned char chMask` in `StyleContext`'s constructor.
3. changed style type from `char` to `int` and added casts for TestLexers.cxx. 
4. changed style type from `char` to `int` for LexCaml.cxx, LexFortran.cxx, LexMagik.cxx, LexPowerPro.cxx, LexProgress.cxx and LexVHDL.cxx.

**Comment by nyamatongwe** [comment]
This appears too disruptive for the limited potential benefit, likely for just `LexHTML`. The change to the meaning of the `initStyle` argument to `Lex` and `Fold` is particularly troubling as it may break independent lexers that currently define states above 127.

The burden of change should be on the beneficiary, so, when `LexHTML` defines states above 127, it can perform the casting or arithmetic necessary to use those new states. That new code and its states will be tested as part of that feature. There are only three calls to `StyleAt` in `LexHTML`, all in the prologue to the styling loop. The `initStyle` argument would also need to be converted.

`LexAccessor` could gain a `StyleIndexAt` method to simplify lexers that want to use styles above 127. Since `BufferStyleAt` is not yet used, it can return an `int` with values above 127.

**Comment by zufuliu** [comment]
OK, adding `StyleIndexAt()` is enough at the moment.
