### ISSUE TITLE
Folding for CMake incorrectly folds functions and elseif

### ISSUE THREAD

**Issue by KeyArts** [ScintillaOrg/lexilla#77]
This issue is copied from 
https://github.com/notepad-plus-plus/notepad-plus-plus/issues/7901 and https://sourceforge.net/p/scintilla/bugs/2213/#25b2

In Summary, the Folding is incorrect, when an elseif-Token is inside the CMake-File.

**Comment by mpheath** [comment]
I tested this patch previously. My test files show how folding 1 `if` block of code can fold the whole document containg 4 separate `if` blocks.

<details>

<summary>Click to display this patch fix this issue:</summary>

![cmake](https://user-images.githubusercontent.com/58158242/164428374-c0362953-7e58-4d66-8179-7bf73dbdcd3c.png)

Can see on the left that the fold column does not go back to `400`. The right side does.

No noticable difference when option `fold.at.else=1` is set which is why the image does not show it.
</details>

The test files:
[lexcmake.zip](https://github.com/ScintillaOrg/lexilla/files/8529954/lexcmake.zip)

and a link to the SourceForge attached file posted by KeyArts that I tested with:
[LexCmake.cxx](https://sourceforge.net/p/scintilla/bugs/_discuss/thread/24e6a4bdaf/25b2/attachment/LexCmake.cxx)

**Comment by nyamatongwe** [comment]
Committed 0422d84ac419c177aa0d20b02267444bccd7a636 which includes the code change from #78 and the test cases linked here.

**Comment by nyamatongwe** [comment]
Included in 5.1.7 release.
