### ISSUE TITLE
the collapse problem in php syntax

### ISSUE THREAD

**Issue by VasaPiterrskiy** [ScintillaOrg/lexilla#8]
it's hard to describe without a demonstration. I 
made a file that demonstrates and explains everything.
copy this text to notepad++ or scylla and everything will become clear
`<?PHP

$b=12;

if (2>$b)
{ // start of block 1
  
  echo'Note';
  ?><div>block 1 enclosed in curly braces can be collapsed</div><?
  print('everything works fine');
  
[PHP_test_1212.txt](https://github.com/ScintillaOrg/lexilla/files/6503337/PHP_test_1212.txt)

} // end of block 1

else
	
{
  echo'if  ?> block <? has multiple lines';	
	
	?>	
	 <div>You cannot collapse the block else{...} in the same way.</div>
	<?	
  print('I think the problem is already clear.');	
}

function PASS($pass) // Press the alt+2 keyboard shortcuts                                     
{

  ?><div>yes a single line interrupt of PHP code does not interrupt the code collapse logic</div><?	

}	

function PASS2($pass)// everything looks beautiful, easy navigation                                     
{

  ?><div>even if several times</div><?	

}

function PASS3($pass)// but if you want to make 1 line break                                     
{

  ?>
  <div>even if several times</div><?	
 ?>
  <div>or more</div><?
  
  
}

function PASS4($pass)// and you will no longer understand what is happening here                                     
{

		?>
			<div>even if several times</div><?	// comment
		$b=100;	
		?>
			<div>or more</div><?

		?>
			<div>
				or very 
				very 
				very 
				much
			</div>
		<?
}
// For the Pascal language, there is a LexPascal.cxx file
// There is no such file for the PHP language. 
// If by analogy with the file LexPascal.cxx
// then need to do something like this
...
else if (sc.Match('?', '>')) { sc.SetState(SCE_PAS_perversionPHP); sc.Forward(); }
...
case SCE_PAS_perversionPHP:
	if (sc.Match('<', '?')) { sc.Forward();	sc.ForwardSetState(SCE_PAS_DEFAULT); }
break;
...

//maybe I'm wrong
//I've never worked for c

`

**Comment by nyamatongwe** [comment]
PHP is normally used in conjunction with HTML and the LexHTML lexer "hypertext" is used for PHP. There is a "phpscript" lexer but this is just like "hypertext" but starts in PHP mode with no need to include a '\<?PHP'.

Some lexers, like LexCPP used for C++ and called "cpp",  provide a 'fold.at.else' option so that an 'else' branch can be folded separately to its 'if'. Some people like this and others prefer treating the whole 'if' as one entity. If anyone wants to contribute a 'fold.hypertext.php.at.else' option then it can be incorporated.

Where you have 'block 1 enclosed in curly braces can be collapsed', folding on line 13 folds away 14,15, and 16; not the whole of block 1 that extends to line 23.

The example stops working at 'function PASS4' since it is not inside a PHP block so is treated as text.

Folding in Scintilla relies on a single fold level for each line. It goes up when a fold increaser like '{' or '\<?' is seen and goes down for a '}' or '?>'. People are often confused because they want there to be a relationship between '{' and '}' or '\<?' and '?\>' but not between '{' and '?\>'.

The outline view seen in the fold margin is a simplification of the underlying level logic. To see the actual levels turn on fold debug mode. In SciTE this is done with the following properties then View | Line Numbers:
~~~properties
fold.flags=64
line.margin.width=10
~~~
There's a column with flags (H=header, W=whitespace) then a 3 digit hex number for the level starting at 0x400. The final column isn't used for PHP.

**Comment by nyamatongwe** [comment]
Its unclear just what problem this issue is reporting. Further explanation is needed.

**Comment by nyamatongwe** [comment]
Closing due to lack of clarity.
