### ISSUE TITLE
Transact-SQL (MS SQL Server): "different per-line styles" after column and table names

### ISSUE THREAD

**Issue by rdipardo** [ScintillaOrg/lexilla#90]
As first reported in #87, LexMSSQL "prefers" the data type style after column and table names, as they typically appear in DDL statements or assignments to typed variables from a query result. This feature achieves tailored styling of type specifiers that may also double as functions, like `CHAR`.

Whitespace is ignored in SQL queries, so the span of characters in the `SCE_MSSQL_DEFAULT_PREF_DATATYPE` state can vary at the end of a line, running afoul of TestLexers:

~~~tsql
/*15*/ SELECT *
/*16*/ FROM Production.Product -- <== elastic region invisibly styled as SCE_MSSQL_DEFAULT_PREF_DATATYPE begins here
/*17*/ ORDER BY Name ASC;
~~~

    ~/../AllStyles.tsql:16: has different per-line styles

The state is only a "virtual" style. It should not appear except by accident, as when editing the T-SQL sample script [provided earlier][0]. Notice how trailing whitespace changes colour after the table and column identifiers `l` and  `l.sid`:

![Examples tsql](https://user-images.githubusercontent.com/59004801/173624138-35b0bb0a-9a99-4e2a-904d-6e62ecf9f4d8.gif)

A previous patch added logic to find EOLs; this new patch simply adds a state reset to the `atEOL` conditional branch to appease the test runner:

[0001-LexMSSQL-Normalize-EOL-style.diff.txt](https://github.com/ScintillaOrg/lexilla/files/8901641/0001-LexMSSQL-Normalize-EOL-style.diff.txt)

This test suite is a lightly edited version of [Sample.zip][0] (with trailing whitespace removed): 

[mssql-AllStyles.zip](https://github.com/ScintillaOrg/lexilla/files/8901642/mssql-AllStyles.zip)

[0]: https://github.com/ScintillaOrg/lexilla/issues/87#issuecomment-1151884040

**Comment by nyamatongwe** [comment]
While more consistent, this makes the styling less correct.

The following example separates the type from the column name with a new line. This wouldn't be common but you could imagine using it with very long column names. 
~~~sql
CREATE TABLE TestTable (
    col
    CHAR(3)
);
~~~

With the current release lexer, when the whole sample is styled in one pass, `CHAR` is `SCE_MSSQL_DATATYPE`. If the `CHAR` line is edited (add a space at start, for example), it switches to `SCE_MSSQL_FUNCTION`.

With the patch, it is always `SCE_MSSQL_FUNCTION`.

The actual problem here is that `SCE_MSSQL_DEFAULT_PREF_DATATYPE` isn't persistent enough and is overwritten with (for example) `styler.ColourTo(i - 1, SCE_MSSQL_DEFAULT);` when the identifier is started on line 3, styling the line end. Switching this to `styler.ColourTo(i - 1, state);` chooses the correct `SCE_MSSQL_DATATYPE` consistently. The cost is that the `SCE_MSSQL_DEFAULT_PREF_DATATYPE` style is used for some whitespace.

![TSQL-Prefer](https://user-images.githubusercontent.com/225818/173705260-b868cf3c-1f92-4243-a980-d26b7cd16e72.png)
[prefer.patch.txt](https://github.com/ScintillaOrg/lexilla/files/8904425/prefer.patch.txt)

An alternative could be to remember a 'prefer data type' flag in line state.

**Comment by rdipardo** [comment]
> [prefer.patch.txt](https://github.com/ScintillaOrg/lexilla/files/8904425/prefer.patch.txt)

That worked well but needed to do the same before operators for the sake of `SCE_MSSQL_VARIABLE`, which likewise triggers a shift into `SCE_MSSQL_DEFAULT_PREF_DATATYPE`:

https://github.com/ScintillaOrg/lexilla/blob/55fa27dcdb6dad26908cced960b4875576efc3a7/lexers/LexMSSQL.cxx#L174-L175

Slippery per-line styles could still occur when operators preceded column identifiers, or line comments followed them:

~~~tsql
/* 29 */ SELECT schema_name
/* 30 */     (tab.schema_id) AS schema_name
/* 31 */     -- retrieve the name, too
/* 32 */     ,tab.name
/* 33 */ FROM sys.tables AS tab;
~~~

     ~/../AllStyles.tsql:29: has different per-line styles

    {9}SELECT{0} {6}schema_name{15}
    {0}    {5}({6}tab.schema_id{5}){0} {9}AS{0} {6}schema_name{15}
    {0}    {2}-- retrieve the name, too{0}
        {5},{6}tab.name{15}
    {9}FROM{0} {6}sys.tables{15} {9}AS{0} {6}tab{5};{0}

I'm sure even more edge cases could be found, but this updated patch at least covers all tested cases:

[0002-LexMSSQL-Honour-datatypes-before-operators.diff.txt](https://github.com/ScintillaOrg/lexilla/files/8924575/0002-LexMSSQL-Honour-datatypes-before-operators.diff.txt)

This updated suite adds core keywords that were previously showing as identifiers:

[0002-mssql-AllStyles.tsql.zip](https://github.com/ScintillaOrg/lexilla/files/8924638/0002-mssql-AllStyles.tsql.zip)

**Comment by rdipardo** [comment]
The correct patch is here: [0003-LexMSSQL-fixup-patch-0002.diff.txt](https://github.com/ScintillaOrg/lexilla/files/8924757/0003-LexMSSQL-fixup-patch-0002.diff.txt)

**Comment by rdipardo** [comment]
Minor revisions, in the interest of testing the last outstanding style (`SCE_MSSQL_STORED_PROCEDURE`):

* add `EXEC` and a stored procedure to keyword lists
* refactor line 11 so the stored procedure's state isn't obscured by `SCE_MSSQL_COLUMN_NAME_2` (it doesn't appear the styles were designed to nest)

[003-AllStyles-incl-SPs.zip](https://github.com/ScintillaOrg/lexilla/files/8926663/003-AllStyles-incl-SPs.zip)

**Comment by nyamatongwe** [comment]
Committed with some more test files: `AllStyles.tsql` is a minimal example of each style; `Issue90.tsql` is the case shown above where `CHAR` flipped styles; `Various.tsql` is the earlier `AllStyles.tsql` with a collection of snippets of Transact-SQL.
